"""empty message

Revision ID: 4a0d73fc2017
Revises: dd7dc641c2b3
Create Date: 2024-03-08 17:44:11.689238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0d73fc2017'
down_revision = 'dd7dc641c2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('planet_name')
        batch_op.drop_column('vehicle_description')
        batch_op.drop_column('caracther_name')
        batch_op.drop_column('caracther_description')
        batch_op.drop_column('vehicle_name')
        batch_op.drop_column('planet_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('caracther_description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('caracther_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
