"""empty message

Revision ID: 6d2a93245eb1
Revises: ff7262246378
Create Date: 2024-03-09 00:01:34.241253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2a93245eb1'
down_revision = 'ff7262246378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('character_description', sa.String(length=250), nullable=True))
        batch_op.drop_column('characther_name')
        batch_op.drop_column('characther_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characther_description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('characther_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('character_description')
        batch_op.drop_column('character_name')

    # ### end Alembic commands ###
