"""empty message

Revision ID: dd7dc641c2b3
Revises: c4ffeae0a4f4
Create Date: 2024-03-08 15:28:25.026846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7dc641c2b3'
down_revision = 'c4ffeae0a4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('planet_description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('caracther_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('caracther_description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('vehicle_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('vehicle_description', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('vehicle_description')
        batch_op.drop_column('vehicle_name')
        batch_op.drop_column('caracther_description')
        batch_op.drop_column('caracther_name')
        batch_op.drop_column('planet_description')
        batch_op.drop_column('planet_name')

    # ### end Alembic commands ###
